name: Docker Image CI

env:
  CODE_SEVER_VERSION: '3.9.1'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image and push
      uses: docker/build-push-action@v2
      with:
        push: ${{ github.ref == 'ref/head/main' }}
        build-args: |
          CODE_SERVER_VERSION=${{ env.CODE_SEVER_VERSION }}
        tags: patrickglass/code-server:latest, patrickglass/code-server:${{ env.CODE_SEVER_VERSION }}
